server:
  port: 8082
spring:
  application:
    name: image-analyzer
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: image-analyzer-group
#      auto-offset-reset: earliest
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: "*"
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

